_target_: hvae.models.HVAE
img_size: ${dataset.img_size}
in_channels: ${dataset.num_channels}
channels: [16, 32, 64]
latent_dim: 16
beta: 0.5
num_levels: 2
lr: 0.0001
residual: false
num_classes: ${dataset.num_classes}