defaults:
 - _self_
 - dataset: cifar10
 - model: dct_hvae

hydra:
  output_subdir: outputs/hydra

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  devices: 1
  enable_checkpointing: false
  enable_progress_bar: false
  gradient_clip_val: 1
  log_every_n_steps: 10
  logger: ${wandb}
  max_epochs: 3000

training:
  batch_size: 256
  num_workers: 8
  lr: 0.001

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: hvae
  save_dir: outputs/wandb
  mode: online
  group: null
  notes: null
  name: null